import Color from 'color';
import EStyleSheet from 'react-native-extended-stylesheet';

export const typography = () => ({
  'text-xs': {fontSize: '0.75rem', lineHeight: '1rem'},
  'text-sm': {fontSize: '0.875rem', lineHeight: '1.25rem'},
  'text-base': {fontSize: '1rem', lineHeight: '1.5rem'},
  'text': {fontFamily: '$defaultFontFamily', fontSize: '1rem', lineHeight: '1.5rem'},
  'text-lg': {fontSize: '1.125rem', lineHeight: '1.75rem'},
  'text-xl': {fontSize: '1.25rem', lineHeight: '1.75rem'},
  'text-2xl': {fontSize: '1.5rem', lineHeight: '2rem'},
  'text-3xl': {fontSize: '1.875rem', lineHeight: '2.25rem'},
  'text-4xl': {fontSize: '2.25rem', lineHeight: '2.5rem'},
  'text-5xl': {fontSize: '3rem', lineHeight: 1},
  'text-6xl': {fontSize: '3.75rem', lineHeight: 1},
  'text-7xl': {fontSize: '4.5rem', lineHeight: 1},
  'text-8xl': {fontSize: '6rem', lineHeight: 1},
  'text-9xl': {fontSize: '8rem', lineHeight: 1},

  'italic': {fontStyle: 'italic'},
  'not-italic': {fontStyle: 'normal'},

  'font-thin': {fontWeight: '100'},
  'font-extralight': {fontWeight: '200'},
  'font-light': {fontWeight: '300'},
  'font-normal': {fontWeight: '400'},
  'font-medium': {fontWeight: '500'},
  'font-semibold': {fontWeight: '600'},
  'font-bold': {fontWeight: '700'},
  'font-extrabold': {fontWeight: '800'},
  'font-black': {fontWeight: '900'},

  'tracking-tighter': {letterSpacing: '$rem * -0.05'},
  'tracking-tight': {letterSpacing: '$rem * -0.025'},
  'tracking-normal': {letterSpacing: 0},
  'tracking-wide': {letterSpacing: '$rem * 0.025'},
  'tracking-wider': {letterSpacing: '$rem * 0.05'},
  'tracking-widest': {letterSpacing: '$rem * 0.1'},

  'leading-3': {lineHeight: '0.75rem'},
  'leading-4': {lineHeight: '1rem'},
  'leading-5': {lineHeight: '1.25rem'},
  'leading-6': {lineHeight: '1.5rem'},
  'leading-7': {lineHeight: '1.75rem'},
  'leading-8': {lineHeight: '2rem'},
  'leading-9': {lineHeight: '2.25rem'},
  'leading-10': {lineHeight: '2.5rem'},
  'leading-none': {lineHeight: 1},
  'leading-tight': {lineHeight: 1.25},
  'leading-snug': {lineHeight: 1.375},
  'leading-normal': {lineHeight: 1.5},
  'leading-relaxed': {lineHeight: 1.625},
  'leading-loose': {lineHeight: 2},

  'text-left': {textAlign: 'left'},
  'text-center': {textAlign: 'center'},
  'text-right': {textAlign: 'right'},
  'text-justify': {textAlign: 'justify'},
  'text-auto': {textAlign: 'auto'},

  'text-transparent': {color: 'transparent'},
  'text-black': {color: '$black'},
  'text-white': {color: '$white'},

  'text-slate-50': {color: '$slate50'},
  'text-slate-100': {color: '$slate100'},
  'text-slate-200': {color: '$slate200'},
  'text-slate-300': {color: '$slate300'},
  'text-slate-400': {color: '$slate400'},
  'text-slate-500': {color: '$slate500'},
  'text-slate-600': {color: '$slate600'},
  'text-slate-700': {color: '$slate700'},
  'text-slate-800': {color: '$slate800'},
  'text-slate-900': {color: '$slate900'},
  'text-gray-50': {color: '$gray50'},
  'text-gray-100': {color: '$gray100'},
  'text-gray-200': {color: '$gray200'},
  'text-gray-300': {color: '$gray300'},
  'text-gray-400': {color: '$gray400'},
  'text-gray-500': {color: '$gray500'},
  'text-gray-600': {color: '$gray600'},
  'text-gray-700': {color: '$gray700'},
  'text-gray-800': {color: '$gray800'},
  'text-gray-900': {color: '$gray900'},
  'text-zinc-50': {color: '$zinc50'},
  'text-zinc-100': {color: '$zinc100'},
  'text-zinc-200': {color: '$zinc200'},
  'text-zinc-300': {color: '$zinc300'},
  'text-zinc-400': {color: '$zinc400'},
  'text-zinc-500': {color: '$zinc500'},
  'text-zinc-600': {color: '$zinc600'},
  'text-zinc-700': {color: '$zinc700'},
  'text-zinc-800': {color: '$zinc800'},
  'text-zinc-900': {color: '$zinc900'},
  'text-neutral-50': {color: '$neutral50'},
  'text-neutral-100': {color: '$neutral100'},
  'text-neutral-200': {color: '$neutral200'},
  'text-neutral-300': {color: '$neutral300'},
  'text-neutral-400': {color: '$neutral400'},
  'text-neutral-500': {color: '$neutral500'},
  'text-neutral-600': {color: '$neutral600'},
  'text-neutral-700': {color: '$neutral700'},
  'text-neutral-800': {color: '$neutral800'},
  'text-neutral-900': {color: '$neutral900'},
  'text-stone-50': {color: '$stone50'},
  'text-stone-100': {color: '$stone100'},
  'text-stone-200': {color: '$stone200'},
  'text-stone-300': {color: '$stone300'},
  'text-stone-400': {color: '$stone400'},
  'text-stone-500': {color: '$stone500'},
  'text-stone-600': {color: '$stone600'},
  'text-stone-700': {color: '$stone700'},
  'text-stone-800': {color: '$stone800'},
  'text-stone-900': {color: '$stone900'},
  'text-red-50': {color: '$red50'},
  'text-red-100': {color: '$red100'},
  'text-red-200': {color: '$red200'},
  'text-red-300': {color: '$red300'},
  'text-red-400': {color: '$red400'},
  'text-red-500': {color: '$red500'},
  'text-red-600': {color: '$red600'},
  'text-red-700': {color: '$red700'},
  'text-red-800': {color: '$red800'},
  'text-red-900': {color: '$red900'},
  'text-orange-50': {color: '$orange50'},
  'text-orange-100': {color: '$orange100'},
  'text-orange-200': {color: '$orange200'},
  'text-orange-300': {color: '$orange300'},
  'text-orange-400': {color: '$orange400'},
  'text-orange-500': {color: '$orange500'},
  'text-orange-600': {color: '$orange600'},
  'text-orange-700': {color: '$orange700'},
  'text-orange-800': {color: '$orange800'},
  'text-orange-900': {color: '$orange900'},
  'text-amber-50': {color: '$amber50'},
  'text-amber-100': {color: '$amber100'},
  'text-amber-200': {color: '$amber200'},
  'text-amber-300': {color: '$amber300'},
  'text-amber-400': {color: '$amber400'},
  'text-amber-500': {color: '$amber500'},
  'text-amber-600': {color: '$amber600'},
  'text-amber-700': {color: '$amber700'},
  'text-amber-800': {color: '$amber800'},
  'text-amber-900': {color: '$amber900'},
  'text-yellow-50': {color: '$yellow50'},
  'text-yellow-100': {color: '$yellow100'},
  'text-yellow-200': {color: '$yellow200'},
  'text-yellow-300': {color: '$yellow300'},
  'text-yellow-400': {color: '$yellow400'},
  'text-yellow-500': {color: '$yellow500'},
  'text-yellow-600': {color: '$yellow600'},
  'text-yellow-700': {color: '$yellow700'},
  'text-yellow-800': {color: '$yellow800'},
  'text-yellow-900': {color: '$yellow900'},
  'text-lime-50': {color: '$lime50'},
  'text-lime-100': {color: '$lime100'},
  'text-lime-200': {color: '$lime200'},
  'text-lime-300': {color: '$lime300'},
  'text-lime-400': {color: '$lime400'},
  'text-lime-500': {color: '$lime500'},
  'text-lime-600': {color: '$lime600'},
  'text-lime-700': {color: '$lime700'},
  'text-lime-800': {color: '$lime800'},
  'text-lime-900': {color: '$lime900'},
  'text-green-50': {color: '$green50'},
  'text-green-100': {color: '$green100'},
  'text-green-200': {color: '$green200'},
  'text-green-300': {color: '$green300'},
  'text-green-400': {color: '$green400'},
  'text-green-500': {color: '$green500'},
  'text-green-600': {color: '$green600'},
  'text-green-700': {color: '$green700'},
  'text-green-800': {color: '$green800'},
  'text-green-900': {color: '$green900'},
  'text-emerald-50': {color: '$emerald50'},
  'text-emerald-100': {color: '$emerald100'},
  'text-emerald-200': {color: '$emerald200'},
  'text-emerald-300': {color: '$emerald300'},
  'text-emerald-400': {color: '$emerald400'},
  'text-emerald-500': {color: '$emerald500'},
  'text-emerald-600': {color: '$emerald600'},
  'text-emerald-700': {color: '$emerald700'},
  'text-emerald-800': {color: '$emerald800'},
  'text-emerald-900': {color: '$emerald900'},
  'text-teal-50': {color: '$teal50'},
  'text-teal-100': {color: '$teal100'},
  'text-teal-200': {color: '$teal200'},
  'text-teal-300': {color: '$teal300'},
  'text-teal-400': {color: '$teal400'},
  'text-teal-500': {color: '$teal500'},
  'text-teal-600': {color: '$teal600'},
  'text-teal-700': {color: '$teal700'},
  'text-teal-800': {color: '$teal800'},
  'text-teal-900': {color: '$teal900'},
  'text-cyan-50': {color: '$cyan50'},
  'text-cyan-100': {color: '$cyan100'},
  'text-cyan-200': {color: '$cyan200'},
  'text-cyan-300': {color: '$cyan300'},
  'text-cyan-400': {color: '$cyan400'},
  'text-cyan-500': {color: '$cyan500'},
  'text-cyan-600': {color: '$cyan600'},
  'text-cyan-700': {color: '$cyan700'},
  'text-cyan-800': {color: '$cyan800'},
  'text-cyan-900': {color: '$cyan900'},
  'text-sky-50': {color: '$sky50'},
  'text-sky-100': {color: '$sky100'},
  'text-sky-200': {color: '$sky200'},
  'text-sky-300': {color: '$sky300'},
  'text-sky-400': {color: '$sky400'},
  'text-sky-500': {color: '$sky500'},
  'text-sky-600': {color: '$sky600'},
  'text-sky-700': {color: '$sky700'},
  'text-sky-800': {color: '$sky800'},
  'text-sky-900': {color: '$sky900'},
  'text-blue-50': {color: '$blue50'},
  'text-blue-100': {color: '$blue100'},
  'text-blue-200': {color: '$blue200'},
  'text-blue-300': {color: '$blue300'},
  'text-blue-400': {color: '$blue400'},
  'text-blue-500': {color: '$blue500'},
  'text-blue-600': {color: '$blue600'},
  'text-blue-700': {color: '$blue700'},
  'text-blue-800': {color: '$blue800'},
  'text-blue-900': {color: '$blue900'},
  'text-indigo-50': {color: '$indigo50'},
  'text-indigo-100': {color: '$indigo100'},
  'text-indigo-200': {color: '$indigo200'},
  'text-indigo-300': {color: '$indigo300'},
  'text-indigo-400': {color: '$indigo400'},
  'text-indigo-500': {color: '$indigo500'},
  'text-indigo-600': {color: '$indigo600'},
  'text-indigo-700': {color: '$indigo700'},
  'text-indigo-800': {color: '$indigo800'},
  'text-indigo-900': {color: '$indigo900'},
  'text-violet-50': {color: '$violet50'},
  'text-violet-100': {color: '$violet100'},
  'text-violet-200': {color: '$violet200'},
  'text-violet-300': {color: '$violet300'},
  'text-violet-400': {color: '$violet400'},
  'text-violet-500': {color: '$violet500'},
  'text-violet-600': {color: '$violet600'},
  'text-violet-700': {color: '$violet700'},
  'text-violet-800': {color: '$violet800'},
  'text-violet-900': {color: '$violet900'},
  'text-purple-50': {color: '$purple50'},
  'text-purple-100': {color: '$purple100'},
  'text-purple-200': {color: '$purple200'},
  'text-purple-300': {color: '$purple300'},
  'text-purple-400': {color: '$purple400'},
  'text-purple-500': {color: '$purple500'},
  'text-purple-600': {color: '$purple600'},
  'text-purple-700': {color: '$purple700'},
  'text-purple-800': {color: '$purple800'},
  'text-purple-900': {color: '$purple900'},
  'text-fuchsia-50': {color: '$fuchsia50'},
  'text-fuchsia-100': {color: '$fuchsia100'},
  'text-fuchsia-200': {color: '$fuchsia200'},
  'text-fuchsia-300': {color: '$fuchsia300'},
  'text-fuchsia-400': {color: '$fuchsia400'},
  'text-fuchsia-500': {color: '$fuchsia500'},
  'text-fuchsia-600': {color: '$fuchsia600'},
  'text-fuchsia-700': {color: '$fuchsia700'},
  'text-fuchsia-800': {color: '$fuchsia800'},
  'text-fuchsia-900': {color: '$fuchsia900'},
  'text-pink-50': {color: '$pink50'},
  'text-pink-100': {color: '$pink100'},
  'text-pink-200': {color: '$pink200'},
  'text-pink-300': {color: '$pink300'},
  'text-pink-400': {color: '$pink400'},
  'text-pink-500': {color: '$pink500'},
  'text-pink-600': {color: '$pink600'},
  'text-pink-700': {color: '$pink700'},
  'text-pink-800': {color: '$pink800'},
  'text-pink-900': {color: '$pink900'},
  'text-rose-50': {color: '$rose50'},
  'text-rose-100': {color: '$rose100'},
  'text-rose-200': {color: '$rose200'},
  'text-rose-300': {color: '$rose300'},
  'text-rose-400': {color: '$rose400'},
  'text-rose-500': {color: '$rose500'},
  'text-rose-600': {color: '$rose600'},
  'text-rose-700': {color: '$rose700'},
  'text-rose-800': {color: '$rose800'},
  'text-rose-900': {color: '$rose900'},

  'no-underline': {textDecorationLine: 'none'},
  'underline': {textDecorationLine: 'underline'},
  'line-through': {textDecorationLine: 'line-through'},
  'underline-line-through': {textDecorationLine: 'underline line-through'},

  'decoration-transparent': {textDecorationColor: 'transparent'},
  'decoration-black': {textDecorationColor: '$black'},
  'decoration-white': {textDecorationColor: '$white'},

  'decoration-slate-50': {textDecorationColor: '$slate50'},
  'decoration-slate-100': {textDecorationColor: '$slate100'},
  'decoration-slate-200': {textDecorationColor: '$slate200'},
  'decoration-slate-300': {textDecorationColor: '$slate300'},
  'decoration-slate-400': {textDecorationColor: '$slate400'},
  'decoration-slate-500': {textDecorationColor: '$slate500'},
  'decoration-slate-600': {textDecorationColor: '$slate600'},
  'decoration-slate-700': {textDecorationColor: '$slate700'},
  'decoration-slate-800': {textDecorationColor: '$slate800'},
  'decoration-slate-900': {textDecorationColor: '$slate900'},
  'decoration-gray-50': {textDecorationColor: '$gray50'},
  'decoration-gray-100': {textDecorationColor: '$gray100'},
  'decoration-gray-200': {textDecorationColor: '$gray200'},
  'decoration-gray-300': {textDecorationColor: '$gray300'},
  'decoration-gray-400': {textDecorationColor: '$gray400'},
  'decoration-gray-500': {textDecorationColor: '$gray500'},
  'decoration-gray-600': {textDecorationColor: '$gray600'},
  'decoration-gray-700': {textDecorationColor: '$gray700'},
  'decoration-gray-800': {textDecorationColor: '$gray800'},
  'decoration-gray-900': {textDecorationColor: '$gray900'},
  'decoration-zinc-50': {textDecorationColor: '$zinc50'},
  'decoration-zinc-100': {textDecorationColor: '$zinc100'},
  'decoration-zinc-200': {textDecorationColor: '$zinc200'},
  'decoration-zinc-300': {textDecorationColor: '$zinc300'},
  'decoration-zinc-400': {textDecorationColor: '$zinc400'},
  'decoration-zinc-500': {textDecorationColor: '$zinc500'},
  'decoration-zinc-600': {textDecorationColor: '$zinc600'},
  'decoration-zinc-700': {textDecorationColor: '$zinc700'},
  'decoration-zinc-800': {textDecorationColor: '$zinc800'},
  'decoration-zinc-900': {textDecorationColor: '$zinc900'},
  'decoration-neutral-50': {textDecorationColor: '$neutral50'},
  'decoration-neutral-100': {textDecorationColor: '$neutral100'},
  'decoration-neutral-200': {textDecorationColor: '$neutral200'},
  'decoration-neutral-300': {textDecorationColor: '$neutral300'},
  'decoration-neutral-400': {textDecorationColor: '$neutral400'},
  'decoration-neutral-500': {textDecorationColor: '$neutral500'},
  'decoration-neutral-600': {textDecorationColor: '$neutral600'},
  'decoration-neutral-700': {textDecorationColor: '$neutral700'},
  'decoration-neutral-800': {textDecorationColor: '$neutral800'},
  'decoration-neutral-900': {textDecorationColor: '$neutral900'},
  'decoration-stone-50': {textDecorationColor: '$stone50'},
  'decoration-stone-100': {textDecorationColor: '$stone100'},
  'decoration-stone-200': {textDecorationColor: '$stone200'},
  'decoration-stone-300': {textDecorationColor: '$stone300'},
  'decoration-stone-400': {textDecorationColor: '$stone400'},
  'decoration-stone-500': {textDecorationColor: '$stone500'},
  'decoration-stone-600': {textDecorationColor: '$stone600'},
  'decoration-stone-700': {textDecorationColor: '$stone700'},
  'decoration-stone-800': {textDecorationColor: '$stone800'},
  'decoration-stone-900': {textDecorationColor: '$stone900'},
  'decoration-red-50': {textDecorationColor: '$red50'},
  'decoration-red-100': {textDecorationColor: '$red100'},
  'decoration-red-200': {textDecorationColor: '$red200'},
  'decoration-red-300': {textDecorationColor: '$red300'},
  'decoration-red-400': {textDecorationColor: '$red400'},
  'decoration-red-500': {textDecorationColor: '$red500'},
  'decoration-red-600': {textDecorationColor: '$red600'},
  'decoration-red-700': {textDecorationColor: '$red700'},
  'decoration-red-800': {textDecorationColor: '$red800'},
  'decoration-red-900': {textDecorationColor: '$red900'},
  'decoration-orange-50': {textDecorationColor: '$orange50'},
  'decoration-orange-100': {textDecorationColor: '$orange100'},
  'decoration-orange-200': {textDecorationColor: '$orange200'},
  'decoration-orange-300': {textDecorationColor: '$orange300'},
  'decoration-orange-400': {textDecorationColor: '$orange400'},
  'decoration-orange-500': {textDecorationColor: '$orange500'},
  'decoration-orange-600': {textDecorationColor: '$orange600'},
  'decoration-orange-700': {textDecorationColor: '$orange700'},
  'decoration-orange-800': {textDecorationColor: '$orange800'},
  'decoration-orange-900': {textDecorationColor: '$orange900'},
  'decoration-amber-50': {textDecorationColor: '$amber50'},
  'decoration-amber-100': {textDecorationColor: '$amber100'},
  'decoration-amber-200': {textDecorationColor: '$amber200'},
  'decoration-amber-300': {textDecorationColor: '$amber300'},
  'decoration-amber-400': {textDecorationColor: '$amber400'},
  'decoration-amber-500': {textDecorationColor: '$amber500'},
  'decoration-amber-600': {textDecorationColor: '$amber600'},
  'decoration-amber-700': {textDecorationColor: '$amber700'},
  'decoration-amber-800': {textDecorationColor: '$amber800'},
  'decoration-amber-900': {textDecorationColor: '$amber900'},
  'decoration-yellow-50': {textDecorationColor: '$yellow50'},
  'decoration-yellow-100': {textDecorationColor: '$yellow100'},
  'decoration-yellow-200': {textDecorationColor: '$yellow200'},
  'decoration-yellow-300': {textDecorationColor: '$yellow300'},
  'decoration-yellow-400': {textDecorationColor: '$yellow400'},
  'decoration-yellow-500': {textDecorationColor: '$yellow500'},
  'decoration-yellow-600': {textDecorationColor: '$yellow600'},
  'decoration-yellow-700': {textDecorationColor: '$yellow700'},
  'decoration-yellow-800': {textDecorationColor: '$yellow800'},
  'decoration-yellow-900': {textDecorationColor: '$yellow900'},
  'decoration-lime-50': {textDecorationColor: '$lime50'},
  'decoration-lime-100': {textDecorationColor: '$lime100'},
  'decoration-lime-200': {textDecorationColor: '$lime200'},
  'decoration-lime-300': {textDecorationColor: '$lime300'},
  'decoration-lime-400': {textDecorationColor: '$lime400'},
  'decoration-lime-500': {textDecorationColor: '$lime500'},
  'decoration-lime-600': {textDecorationColor: '$lime600'},
  'decoration-lime-700': {textDecorationColor: '$lime700'},
  'decoration-lime-800': {textDecorationColor: '$lime800'},
  'decoration-lime-900': {textDecorationColor: '$lime900'},
  'decoration-green-50': {textDecorationColor: '$green50'},
  'decoration-green-100': {textDecorationColor: '$green100'},
  'decoration-green-200': {textDecorationColor: '$green200'},
  'decoration-green-300': {textDecorationColor: '$green300'},
  'decoration-green-400': {textDecorationColor: '$green400'},
  'decoration-green-500': {textDecorationColor: '$green500'},
  'decoration-green-600': {textDecorationColor: '$green600'},
  'decoration-green-700': {textDecorationColor: '$green700'},
  'decoration-green-800': {textDecorationColor: '$green800'},
  'decoration-green-900': {textDecorationColor: '$green900'},
  'decoration-emerald-50': {textDecorationColor: '$emerald50'},
  'decoration-emerald-100': {textDecorationColor: '$emerald100'},
  'decoration-emerald-200': {textDecorationColor: '$emerald200'},
  'decoration-emerald-300': {textDecorationColor: '$emerald300'},
  'decoration-emerald-400': {textDecorationColor: '$emerald400'},
  'decoration-emerald-500': {textDecorationColor: '$emerald500'},
  'decoration-emerald-600': {textDecorationColor: '$emerald600'},
  'decoration-emerald-700': {textDecorationColor: '$emerald700'},
  'decoration-emerald-800': {textDecorationColor: '$emerald800'},
  'decoration-emerald-900': {textDecorationColor: '$emerald900'},
  'decoration-teal-50': {textDecorationColor: '$teal50'},
  'decoration-teal-100': {textDecorationColor: '$teal100'},
  'decoration-teal-200': {textDecorationColor: '$teal200'},
  'decoration-teal-300': {textDecorationColor: '$teal300'},
  'decoration-teal-400': {textDecorationColor: '$teal400'},
  'decoration-teal-500': {textDecorationColor: '$teal500'},
  'decoration-teal-600': {textDecorationColor: '$teal600'},
  'decoration-teal-700': {textDecorationColor: '$teal700'},
  'decoration-teal-800': {textDecorationColor: '$teal800'},
  'decoration-teal-900': {textDecorationColor: '$teal900'},
  'decoration-cyan-50': {textDecorationColor: '$cyan50'},
  'decoration-cyan-100': {textDecorationColor: '$cyan100'},
  'decoration-cyan-200': {textDecorationColor: '$cyan200'},
  'decoration-cyan-300': {textDecorationColor: '$cyan300'},
  'decoration-cyan-400': {textDecorationColor: '$cyan400'},
  'decoration-cyan-500': {textDecorationColor: '$cyan500'},
  'decoration-cyan-600': {textDecorationColor: '$cyan600'},
  'decoration-cyan-700': {textDecorationColor: '$cyan700'},
  'decoration-cyan-800': {textDecorationColor: '$cyan800'},
  'decoration-cyan-900': {textDecorationColor: '$cyan900'},
  'decoration-sky-50': {textDecorationColor: '$sky50'},
  'decoration-sky-100': {textDecorationColor: '$sky100'},
  'decoration-sky-200': {textDecorationColor: '$sky200'},
  'decoration-sky-300': {textDecorationColor: '$sky300'},
  'decoration-sky-400': {textDecorationColor: '$sky400'},
  'decoration-sky-500': {textDecorationColor: '$sky500'},
  'decoration-sky-600': {textDecorationColor: '$sky600'},
  'decoration-sky-700': {textDecorationColor: '$sky700'},
  'decoration-sky-800': {textDecorationColor: '$sky800'},
  'decoration-sky-900': {textDecorationColor: '$sky900'},
  'decoration-blue-50': {textDecorationColor: '$blue50'},
  'decoration-blue-100': {textDecorationColor: '$blue100'},
  'decoration-blue-200': {textDecorationColor: '$blue200'},
  'decoration-blue-300': {textDecorationColor: '$blue300'},
  'decoration-blue-400': {textDecorationColor: '$blue400'},
  'decoration-blue-500': {textDecorationColor: '$blue500'},
  'decoration-blue-600': {textDecorationColor: '$blue600'},
  'decoration-blue-700': {textDecorationColor: '$blue700'},
  'decoration-blue-800': {textDecorationColor: '$blue800'},
  'decoration-blue-900': {textDecorationColor: '$blue900'},
  'decoration-indigo-50': {textDecorationColor: '$indigo50'},
  'decoration-indigo-100': {textDecorationColor: '$indigo100'},
  'decoration-indigo-200': {textDecorationColor: '$indigo200'},
  'decoration-indigo-300': {textDecorationColor: '$indigo300'},
  'decoration-indigo-400': {textDecorationColor: '$indigo400'},
  'decoration-indigo-500': {textDecorationColor: '$indigo500'},
  'decoration-indigo-600': {textDecorationColor: '$indigo600'},
  'decoration-indigo-700': {textDecorationColor: '$indigo700'},
  'decoration-indigo-800': {textDecorationColor: '$indigo800'},
  'decoration-indigo-900': {textDecorationColor: '$indigo900'},
  'decoration-violet-50': {textDecorationColor: '$violet50'},
  'decoration-violet-100': {textDecorationColor: '$violet100'},
  'decoration-violet-200': {textDecorationColor: '$violet200'},
  'decoration-violet-300': {textDecorationColor: '$violet300'},
  'decoration-violet-400': {textDecorationColor: '$violet400'},
  'decoration-violet-500': {textDecorationColor: '$violet500'},
  'decoration-violet-600': {textDecorationColor: '$violet600'},
  'decoration-violet-700': {textDecorationColor: '$violet700'},
  'decoration-violet-800': {textDecorationColor: '$violet800'},
  'decoration-violet-900': {textDecorationColor: '$violet900'},
  'decoration-purple-50': {textDecorationColor: '$purple50'},
  'decoration-purple-100': {textDecorationColor: '$purple100'},
  'decoration-purple-200': {textDecorationColor: '$purple200'},
  'decoration-purple-300': {textDecorationColor: '$purple300'},
  'decoration-purple-400': {textDecorationColor: '$purple400'},
  'decoration-purple-500': {textDecorationColor: '$purple500'},
  'decoration-purple-600': {textDecorationColor: '$purple600'},
  'decoration-purple-700': {textDecorationColor: '$purple700'},
  'decoration-purple-800': {textDecorationColor: '$purple800'},
  'decoration-purple-900': {textDecorationColor: '$purple900'},
  'decoration-fuchsia-50': {textDecorationColor: '$fuchsia50'},
  'decoration-fuchsia-100': {textDecorationColor: '$fuchsia100'},
  'decoration-fuchsia-200': {textDecorationColor: '$fuchsia200'},
  'decoration-fuchsia-300': {textDecorationColor: '$fuchsia300'},
  'decoration-fuchsia-400': {textDecorationColor: '$fuchsia400'},
  'decoration-fuchsia-500': {textDecorationColor: '$fuchsia500'},
  'decoration-fuchsia-600': {textDecorationColor: '$fuchsia600'},
  'decoration-fuchsia-700': {textDecorationColor: '$fuchsia700'},
  'decoration-fuchsia-800': {textDecorationColor: '$fuchsia800'},
  'decoration-fuchsia-900': {textDecorationColor: '$fuchsia900'},
  'decoration-pink-50': {textDecorationColor: '$pink50'},
  'decoration-pink-100': {textDecorationColor: '$pink100'},
  'decoration-pink-200': {textDecorationColor: '$pink200'},
  'decoration-pink-300': {textDecorationColor: '$pink300'},
  'decoration-pink-400': {textDecorationColor: '$pink400'},
  'decoration-pink-500': {textDecorationColor: '$pink500'},
  'decoration-pink-600': {textDecorationColor: '$pink600'},
  'decoration-pink-700': {textDecorationColor: '$pink700'},
  'decoration-pink-800': {textDecorationColor: '$pink800'},
  'decoration-pink-900': {textDecorationColor: '$pink900'},
  'decoration-rose-50': {textDecorationColor: '$rose50'},
  'decoration-rose-100': {textDecorationColor: '$rose100'},
  'decoration-rose-200': {textDecorationColor: '$rose200'},
  'decoration-rose-300': {textDecorationColor: '$rose300'},
  'decoration-rose-400': {textDecorationColor: '$rose400'},
  'decoration-rose-500': {textDecorationColor: '$rose500'},
  'decoration-rose-600': {textDecorationColor: '$rose600'},
  'decoration-rose-700': {textDecorationColor: '$rose700'},
  'decoration-rose-800': {textDecorationColor: '$rose800'},
  'decoration-rose-900': {textDecorationColor: '$rose900'},

  'decoration-solid': {textDecorationStyle: 'solid'},
  'decoration-double': {textDecorationStyle: 'double'},
  'decoration-dotted': {textDecorationStyle: 'dotted'},
  'decoration-dashed': {textDecorationStyle: 'dashed'},

  'uppercase': {textTransform: 'uppercase'},
  'lowercase': {textTransform: 'lowercase'},
  'capitalize': {textTransform: 'capitalize'},
  'normal-case': {textTransform: 'none'},

  /**/
  'text-blue': {color: '$blue'},
  'text-indigo': {color: '$indigo'},
  'text-purple': {color: '$purple'},
  'text-pink': {color: '$pink'},
  'text-red': {color: '$red'},
  'text-orange': {color: '$orange'},
  'text-yellow': {color: '$yellow'},
  'text-green': {color: '$green'},
  'text-teal': {color: '$teal'},
  'text-cyan': {color: '$cyan'},
  'text-gray': {color: '$gray'},
  'text-primary': {color: '$primary'},
  'text-secondary': {color: '$secondary'},
  'text-success': {color: '$success'},
  'text-info': {color: '$info'},
  'text-warning': {color: '$warning'},
  'text-danger': {color: '$danger'},
  'text-dark': {color: '$dark'},
  'text-light': {color: '$textLight'},
  'text-gray-1': {color: '$gray1'},
  'text-gray-2': {color: '$gray2'},
  'text-gray-3': {color: '$gray3'},
  'text-gray-4': {color: '$gray4'},
  'text-gray-5': {color: '$gray5'},
  'text-gray-dark': {color: '$grayDark'},
  'text-50': {color: Color(EStyleSheet.value('$text')).lighten(0.5).hex()},
  'text-light-50': {color: Color(EStyleSheet.value('$textLight')).lighten(0.75).hex()},
  'h1': {
    fontFamily: '$defaultFontFamily',
    fontSize: '3rem',
    fontWeight: 'bold',
    paddingVertical: '1rem',
    color: '$text',
  },
  'h2': {
    fontFamily: '$defaultFontFamily',
    fontSize: '2.5rem',
    fontWeight: 'bold',
    paddingVertical: '1rem',
    color: '$text',
  },
  'h3': {
    fontFamily: '$defaultFontFamily',
    fontSize: '2rem',
    fontWeight: 'bold',
    paddingVertical: '1rem',
    color: '$text',
  },
  'h4': {
    fontFamily: '$defaultFontFamily',
    fontSize: '1.6rem',
    fontWeight: 'bold',
    paddingVertical: '1rem',
    color: '$text',
  },
  'h5': {
    fontFamily: '$defaultFontFamily',
    fontSize: '1.2rem',
    fontWeight: 'bold',
    paddingVertical: '1rem',
    color: '$text',
  },
  'h6': {
    fontFamily: '$defaultFontFamily',
    fontSize: '1rem',
    fontWeight: 'bold',
    paddingVertical: '1rem',
    color: '$text',
  },
  'statusbar-space': {},
  'text-md': {fontSize: '1.48rem'},
  'text-title': {fontSize: '1.8rem'},
  'text-subtitle': {fontSize: '1.4rem'},
  'text-btn': {fontSize: '1.16rem'},
  'text-bold': {fontWeight: 'bold'},
  'text-disabled': {color: Color(EStyleSheet.value('$textLight')).lighten(0.5).hex()},
  'text-link': {textDecorationLine: 'underline'},
  'text-align-left': {textAlign: 'left'},
  'text-align-right': {textAlign: 'right'},
  'text-align-center': {textAlign: 'center'},

});
