/**
 * More info about extended stylesheet visit:
 * @link https://github.com/vitalets/react-native-extended-stylesheet
 */
import EStyleSheet from 'react-native-extended-stylesheet';
import Color from 'color';

const defaultClasses = {

    // Accordion
    'accordion-body': {},
    'accordion-button': {},
    'accordion-collapse': {},
    'accordion-flush': {},
    'accordion-header': {},
    'accordion-item': {},
    'collapsed': {},

    // Alerts
    'alert-danger': {},
    'alert-dark': {},
    'alert-dismissible': {},
    'alert-heading': {},
    'alert-info': {},
    'alert-light': {},
    'alert-link': {},
    'alert-primary': {},
    'alert-secondary': {},
    'alert-success': {},
    'alert-warning': {},
    'fade': {},

    // Badges
    'badge': {
        backgroundColor: '$primary',
        padding: '0.5rem',
        marginVertical: 1,
        borderRadius: 28,
        minWidth: 28,
        color: '$white',
        fontWeight: 'bold',
        alignItems: 'center',
        justifyContent: 'center',
        textAlign: 'center',

    },
    'badge-danger': {},
    'badge-dark': {},
    'badge-info': {},
    'badge-light': {},
    'badge-pill': {},
    'badge-primary': {},
    'badge-secondary': {},
    'badge-success': {},
    'badge-warning': {},

    // Borders
    'border': {},
    'border-*-0': {},
    'border-1': {},
    'border-danger': {},
    'border-dark': {},
    'border-info': {},
    'border-light': {},
    'border-primary': {},
    'border-secondary': {},
    'border-success': {},
    'border-warning': {},
    'border-white': {},


    /**
     * Rounded
     */
    'rounded': {borderRadius: '9999rem'},
    'rounded-1': {borderRadius: 1},
    'rounded-2': {borderRadius: 2},
    'rounded-3': {borderRadius: 3},
    'rounded-4': {borderRadius: 4},
    'rounded-5': {borderRadius: 5},
    'rounded-6': {borderRadius: 6},
    'rounded-7': {borderRadius: 7},
    'rounded-8': {borderRadius: 8},
    'rounded-10': {borderRadius: 10},
    'rounded-16': {borderRadius: 8},
    'rounded-24': {borderRadius: 8},
    'rounded-32': {borderRadius: 8},

    'rounded-1-rem': {borderRadius: '1rem'},
    'rounded-2-rem': {borderRadius: '2rem'},
    'rounded-3-rem': {borderRadius: '3rem'},
    'rounded-4-rem': {borderRadius: '4rem'},
    'rounded-5-rem': {borderRadius: '5rem'},

    'rounded-left-5': {borderBottomLeftRadius: 5, borderTopLeftRadius: 5},
    'rounded-right-5': {borderBottomRightRadius: 5, borderTopRightRadius: 5},
    'rounded-top-left-5': {borderTopLeftRadius: 5},
    'rounded-top-right-5': {borderTopRightRadius: 5},
    'rounded-top-x-5': {borderTopLeftRadius: 5, borderTopRightRadius: 5},
    'rounded-top-x-2rem': {borderTopLeftRadius: '2rem', borderTopRightRadius: '2rem'},
    'rounded-bottom-x-2rem': {borderBottomLeftRadius: '2rem', borderBottomRightRadius: '2rem'},


    'rounded-*': {},
    'rounded-0': {},
    'rounded-bottom': {},
    'rounded-circle': {},
    'rounded-end': {},
    'rounded-pill': {},
    'rounded-start': {},
    'rounded-top': {},

    // Breadcrumbs
    'breadcrumb': {},
    'breadcrumb-item': {},

    // Button Groups
    'btn-group': {},
    'btn-group (nested)': {},
    'btn-group-lg': {},
    'btn-group-sm': {},
    'btn-group-vertical': {},
    'btn-toolbar': {},

    // Button Modifiers
    'active button': {},
    'btn-block': {},
    'btn-lg': {},
    'btn-sm': {},
    'checkbox as button': {},
    'disabled button': {},
    'radio as button': {},

    // Buttons
    'btn': {
        borderWidth: 1,
        // borderColor: Color(EStyleSheet.value('$primary')).darken(0.16).hex(),
    },
    'btn-close': {},
    'btn-close-white': {},
    'btn-danger': {},
    'btn-dark': {},
    'btn-info': {},
    'btn-light': {},
    'btn-link': {},
    'btn-outline-danger': {},
    'btn-outline-dark': {},
    'btn-outline-info': {},
    'btn-outline-light': {},
    'btn-outline-primary': {},
    'btn-outline-secondary': {},
    'btn-outline-success': {},
    'btn-outline-warning': {},
    'btn-primary': {},
    'btn-secondary': {},
    'btn-success': {},
    'btn-warning': {},

    // Cards
    'card': {
        backgroundColor: '$white',
        borderRadius: 5,
        shadowOpacity: 0.16,
        shadowRadius: 4,
        shadowOffset: {
            height: 4,
            width: 0,
        },
        elevation: 4,
    },
    'card bg-... text-...': {},
    'card-body': {},
    'card-columns': {},
    'card-deck': {},
    'card-footer': {},
    'card-group': {},
    'card-header': {},
    'card-header-pills': {},
    'card-header-tabs': {},
    'card-img-bottom': {},
    'card-img-overlay': {},
    'card-img-top': {},
    'card-link': {},
    'card-subtitle': {},
    'card-text': {},
    'card-title': {},
    'h*.card-header': {},
    'middle image': {},
    'stretched-link': {},

    // Carousel
    'carousel slide': {},
    'carousel-caption': {},
    'carousel-control-next': {},
    'carousel-control-next-icon': {},
    'carousel-control-prev': {},
    'carousel-control-prev-icon': {},
    'carousel-dark': {},
    'carousel-fade': {},
    'carousel-indicators': {},
    'carousel-inner': {},
    'carousel-item': {},

    // Collapse
    'accordion': {},
    'collapse': {},

    // Colors
    'bg-primary': {backgroundColor: '$primary'},
    'bg-success': {backgroundColor: '$success'},
    'bg-red': {backgroundColor: '$danger'},
    'bg-danger': {backgroundColor: '$danger'},
    'bg-green': {backgroundColor: '$success'},
    'bg-orange': {backgroundColor: '$orange'},
    'bg-yellow': {backgroundColor: '$warning'},
    'bg-gray-1': {backgroundColor: '$gray1'},
    'bg-gray-2': {backgroundColor: '$gray2'},
    'bg-gray-3': {backgroundColor: '$gray3'},
    'bg-gray-4': {backgroundColor: '$gray4'},
    'bg-gray-5': {backgroundColor: '$gray5'},
    'bg-purple': {backgroundColor: '$purple'},
    'bg-black': {backgroundColor: '$black'},
    'bg-body': {},
    'bg-dark': {},
    'bg-gradient': {},
    'bg-info': {},
    'bg-light': {},
    'bg-secondary': {},
    'bg-transparent': {backgroundColor: 'transparent'},
    'bg-warning': {backgroundColor: '$warning'},
    'bg-white': {
        backgroundColor: '$white',
    },
    'link-danger': {},
    'link-dark': {},
    'link-info': {},
    'link-light': {},
    'link-primary': {},
    'link-secondary': {},
    'link-success': {},
    'link-warning': {},
    'text-dark': {},
    'text-info': {},
    'text-light': {},
    'text-primary': {
        color: '$primary',
    },
    'text-secondary': {},
    'text-warning': {color: '$warning'},
    'text-danger': {color: '$danger'},
    'text-success': {color: '$success'},
    'text-white': {
        color: '$white',
    },
    // Custom Forms
    'custom-checkbox': {},
    'custom-file': {},
    'custom-radio': {},
    'custom-range': {},
    'custom-select': {},
    'custom-switch': {},

    // Display
    'd-*-block': {},
    'd-*-flex': {},
    'd-*-inline': {},
    'd-*-inline-block': {},
    'd-*-inline-flex': {},
    'd-*-none': {},
    'd-*-table': {},
    'd-*-table-cell': {},
    'd-grid': {},
    'd-lg-grid': {},
    'd-lg-table-row': {},
    'd-md-grid': {},
    'd-md-table-row': {},
    'd-print-...': {},
    'd-print-flex': {},
    'd-print-grid': {},
    'd-print-inline-flex': {},
    'd-print-table': {},
    'd-print-table-cell': {},
    'd-print-table-row': {},
    'd-sm-grid': {},
    'd-sm-table-row': {},
    'd-table-row': {},
    'd-xl-grid': {},
    'd-xl-table-row': {},
    'd-xxl-block': {},
    'd-xxl-flex': {},
    'd-xxl-grid': {},
    'd-xxl-inline': {},
    'd-xxl-inline-block': {},
    'd-xxl-inline-flex': {},
    'd-xxl-none': {},
    'd-xxl-table': {},
    'd-xxl-table-cell': {},
    'd-xxl-table-row': {},

    // Dropdowns
    'dropdown': {},
    'dropdown (split)': {},
    'dropdown-divider': {},
    'dropdown-header': {},
    'dropdown-item': {},
    'dropdown-item disabled': {},
    'dropdown-item-text': {},
    'dropdown-menu': {},
    'dropdown-menu-dark': {},
    'dropdown-menu-end': {},
    'dropdown-menu-lg-end': {},
    'dropdown-menu-lg-start': {},
    'dropdown-menu-md-end': {},
    'dropdown-menu-md-start': {},
    'dropdown-menu-right': {},
    'dropdown-menu-sm-end': {},
    'dropdown-menu-sm-start': {},
    'dropdown-menu-start': {},
    'dropdown-menu-xl-end': {},
    'dropdown-menu-xl-start': {},
    'dropdown-toggle': {},
    'dropdown-toggle-split': {},
    'dropleft': {},
    'dropright': {},
    'dropup': {},
    'dropup (split)': {},

    // Figure
    'figure': {},
    'figure-caption': {},
    'figure-img': {},

    // Flexbox
    'align-content-*-around': {},
    'align-content-*-center': {},
    'align-content-*-end': {},
    'align-content-*-start': {},
    'align-content-*-stretch': {},
    'align-items-*-baseline': {},
    'align-items-*-center': {},
    'align-items-*-end': {},
    'align-items-*-start': {},
    'align-items-*-stretch': {},
    'align-self-*-baseline': {},
    'align-self-*-center': {},
    'align-self-*-end': {},
    'align-self-*-start': {},
    'align-self-*-stretch': {},
    'flex-*-column': {},
    'flex-*-column-reverse': {},
    'flex-*-grow-0': {},
    'flex-*-grow-1': {},
    'flex-*-nowrap': {},
    'flex-*-row': {},
    'flex-*-row-reverse': {},
    'flex-*-shrink-0': {},
    'flex-*-shrink-1': {},
    'flex-*-wrap': {},
    'flex-*-wrap-reverse': {},
    'flex-fill': {},
    'flex-lg-fill': {},
    'flex-md-fill': {},
    'flex-sm-fill': {},
    'flex-xl-fill': {},
    'flex-xxl-column': {},
    'flex-xxl-column-reverse': {},
    'flex-xxl-fill': {},
    'flex-xxl-grow-0': {},
    'flex-xxl-grow-1': {},
    'flex-xxl-nowrap': {},
    'flex-xxl-row': {},
    'flex-xxl-row-reverse': {},
    'flex-xxl-shrink-0': {},
    'flex-xxl-shrink-1': {},
    'flex-xxl-wrap': {},
    'flex-xxl-wrap-reverse': {},
    'justify-content-*-around': {},
    'justify-content-*-between': {},
    'justify-content-*-center': {},
    'justify-content-*-end': {},
    'justify-content-*-start': {},
    'justify-content-around': {},
    'justify-content-between': {},
    'justify-content-center': {
        justifyContent: 'center',
    },
    'justify-content-end': {},
    'justify-content-evenly': {},
    'justify-content-lg-around': {},
    'justify-content-lg-between': {},
    'justify-content-lg-center': {},
    'justify-content-lg-end': {},
    'justify-content-lg-evenly': {},
    'justify-content-lg-start': {},
    'justify-content-md-around': {},
    'justify-content-md-between': {},
    'justify-content-md-center': {},
    'justify-content-md-end': {},
    'justify-content-md-evenly': {},
    'justify-content-md-start': {},
    'justify-content-sm-around': {},
    'justify-content-sm-between': {},
    'justify-content-sm-center': {},
    'justify-content-sm-end': {},
    'justify-content-sm-evenly': {},
    'justify-content-sm-start': {},
    'justify-content-start': {},
    'justify-content-xl-around': {},
    'justify-content-xl-between': {},
    'justify-content-xl-center': {},
    'justify-content-xl-end': {},
    'justify-content-xl-evenly': {},
    'justify-content-xl-start': {},
    'justify-content-xxl-around': {},
    'justify-content-xxl-between': {},
    'justify-content-xxl-center': {},
    'justify-content-xxl-end': {},
    'justify-content-xxl-evenly': {},
    'justify-content-xxl-start': {},
    'order-*-#': {},
    'order-0': {},
    'order-1': {},
    'order-first': {},
    'order-last': {},
    'order-lg-0': {},
    'order-lg-first': {},
    'order-lg-last': {},
    'order-md-0': {},
    'order-md-first': {},
    'order-md-last': {},
    'order-sm-0': {},
    'order-sm-first': {},
    'order-sm-last': {},
    'order-xl-0': {},
    'order-xl-first': {},
    'order-xl-last': {},
    'order-xxl-0': {},
    'order-xxl-first': {},
    'order-xxl-last': {},

    // Form Input Groups
    'checkbox': {},
    'input-group': {},
    'input-group-append': {},
    'input-group-lg': {},
    'input-group-prepend': {},
    'input-group-sm': {},
    'radio': {},
    'segmented buttons': {},

    // Forms
    'col-form-label': {},
    'col-form-label-lg': {},
    'col-form-label-sm': {},
    'disabled items': {},
    'form using the grid': {},
    'form-check': {},
    'form-check-inline': {},
    'form-check-input': {},
    'form-check-label': {},
    'form-control': {},
    'form-control-color': {},
    'form-control-file': {},
    'form-control-lg': {},
    'form-control-plaintext': {},
    'form-control-range': {},
    'form-control-sm': {},
    'form-floating': {},
    'form-group': {},
    'form-inline': {},
    'form-label': {},
    'form-select': {},
    'form-select-lg': {},
    'form-select-sm': {},
    'form-switch': {},
    'form-text': {},
    'input-group-text': {},
    'is-invalid': {},
    'is-valid': {},
    'readonly': {},
    'valid-feedback': {},
    'valid-tooltip': {},

    // Grid
    'col': {
        flexDirection: 'column',
    },
    'col-*': {},
    'col-# (<576px)': {},
    'col-1': {},
    'col-10': {},
    'col-11': {},
    'col-12': {},
    'col-2': {},
    'col-3': {},
    'col-4': {},
    'col-5': {},
    'col-6': {},
    'col-7': {},
    'col-8': {},
    'col-9': {},
    'col-auto': {},
    'col-lg-# (≥992px)': {},
    'col-lg-1': {},
    'col-md-# (≥768px)': {},
    'col-md-1': {},
    'col-sm-# (≥576px)': {},
    'col-sm-1': {},
    'col-xl-# (≥1200px)': {},
    'col-xl-1': {},
    'col-xxl-1': {},
    'container': {
        flex: 1,
        backgroundColor: '$white',
    },
    'container-fluid': {},
    'container-sm': {},
    'container-lg': {},
    'container-md': {},
    'container-xl': {},
    'container-xxl': {},
    'g-0': {},
    'g-lg-0': {},
    'g-md-0': {},
    'g-sm-0': {},
    'g-xl-0': {},
    'g-xxl-0': {},
    'gap-0': {},
    'gap-lg-0': {},
    'gap-md-0': {},
    'gap-sm-0': {},
    'gap-xl-0': {},
    'gap-xxl-0': {},
    'gx-0': {},
    'gx-lg-0': {},
    'gx-md-0': {},
    'gx-sm-0': {},
    'gx-xl-0': {},
    'gx-xxl-0': {},
    'gy-xxl-0': {},
    'nested columns': {},
    'no-gutters': {},
    'offset-*-#': {},
    'offset-0': {},
    'offset-lg-0': {},
    'offset-md-0': {},
    'offset-xxl-0': {},
    'order-#': {},
    'row': {
        flexDirection: 'row',
    },
    'row-cols-1': {},
    'row-cols-auto': {},
    'row-cols-lg-1': {},
    'row-cols-lg-auto': {},
    'row-cols-md-1': {},
    'row-cols-md-auto': {},
    'row-cols-sm-1': {},
    'row-cols-sm-auto': {},
    'row-cols-xl-1': {},
    'row-cols-xl-auto': {},
    'row-cols-xxl-1': {},
    'row-cols-xxl-auto': {},

    // Images
    'img-fluid': {},
    'img-thumbnail': {},

    // Jumbotron
    'jumbotron': {},
    'jumbotron-fluid': {},

    // List Group
    'list-group': {},
    'list-group with badges': {},
    'list-group with d-flex': {},
    'list-group-item active': {},
    'list-group-item disabled': {},
    'list-group-item-action': {},
    'list-group-item-danger': {},
    'list-group-item-dark': {},
    'list-group-item-info': {},
    'list-group-item-light': {},
    'list-group-item-primary': {},
    'list-group-item-secondary': {},
    'list-group-item-success': {},
    'list-group-item-warning': {},

    // List group
    'list-group-flush': {},
    'list-group-horizontal': {},
    'list-group-horizontal-lg': {},
    'list-group-horizontal-md': {},
    'list-group-horizontal-sm': {},
    'list-group-horizontal-xl': {},
    'list-group-horizontal-xxl': {},
    'list-group-item': {},

    // Media Objects
    'd-flex align-self-center': {},
    'd-flex align-self-end': {},
    'd-flex align-self-start': {},
    'media': {},
    'nested media': {},
    'right aligned media': {},

    // Misc
    'close': {},
    'embed-responsive': {},
    'initialism': {},
    'invisible': {},
    'overflow-auto': {},
    'overflow-hidden': {},
    'overflow-scroll': {},
    'overflow-visible': {},
    'pe-auto': {},
    'pe-none': {},
    'shadow': {
        shadowOpacity: 0.16,
        shadowRadius: 4,
        shadowOffset: {
            height: 4,
            width: 0,
        },
        elevation: 4,
    },
    'shadow-lg': {},
    'shadow-none': {},
    'shadow-sm': {},
    'sr-only': {},
    'sr-only-focusable': {},
    'visible': {},
    'visually-hidden': {},
    'visually-hidden-focusable': {},

    // Modal
    'modal': {},
    'modal fade': {},
    'modal-dialog-centered': {},
    'modal-lg': {},
    'modal-sm': {},
    'modal-xl': {},

    // Modals
    'modal-body': {},
    'modal-contant': {},
    'modal-dialog': {},
    'modal-dialog-scrollable': {},
    'modal-footer': {},
    'modal-fullscreen': {},
    'modal-fullscreen-lg-down': {},
    'modal-fullscreen-md-down': {},
    'modal-fullscreen-sm-down': {},
    'modal-fullscreen-xl-down': {},
    'modal-fullscreen-xxl-down': {},
    'modal-header': {},
    'modal-static': {},
    'modal-title': {},

    // Navbar
    'collapse navbar-collapse': {},
    'nav-item': {},
    'nav-link': {},
    'navbar': {},
    'navbar fixed-bottom': {},
    'navbar fixed-top': {},
    'navbar sticky-top': {},
    'navbar with form': {},
    'navbar-brand': {},
    'navbar-collapse': {},
    'navbar-dark': {},
    'navbar-dark bg-dark': {},
    'navbar-expand-*': {},
    'navbar-expand-lg': {},
    'navbar-expand-md': {},
    'navbar-expand-sm': {},
    'navbar-expand-xl': {},
    'navbar-expand-xxl': {},
    'navbar-light': {},
    'navbar-nav': {},
    'navbar-text': {},
    'navbar-toggler': {},
    'navbar-toggler-icon': {},

    // Navs
    'nav flex-column': {},
    'nav justify-content-*': {},
    'nav with flex utils': {},
    'nav-fill': {},
    'nav-justified': {},
    'nav-pills': {},
    'nav-pills with dropdown': {},
    'nav-tabs': {},
    'nav-tabs with dropdown': {},
    'nav.nav': {},
    'tab-content': {},
    'tab-pane': {},
    'ul.nav': {},

    // Pagination
    'page-item active': {},
    'page-item disabled': {},
    'pagination': {},
    'pagination-lg': {},
    'pagination-sm': {},
    '        opover': {},
    'dismissible popover': {},
    'popovers': {},
    '        ositioning': {},
    'align-*': {},


    'bottom-0': {bottom: '0rem'},
    'bottom-1': {bottom: '1rem'},
    'bottom-2': {bottom: '2rem'},
    'bottom-3': {bottom: '3rem'},
    'bottom-4': {bottom: '4rem'},
    'bottom-5': {bottom: '5rem'},
    'bottom-6': {bottom: '6rem'},
    'bottom-7': {bottom: '7rem'},
    'bottom-8': {bottom: '8rem'},
    'bottom-9': {bottom: '9rem'},
    'bottom-10': {bottom: '10rem'},
    'bottom-11': {bottom: '11rem'},
    'bottom-12': {bottom: '12rem'},
    'bottom-13': {bottom: '13rem'},
    'bottom-14': {bottom: '14rem'},
    'bottom-15': {bottom: '15rem'},
    'bottom-16': {bottom: '16rem'},


    'bottom-100': {},
    'bottom-50': {},
    'clearfix': {},
    'end-0': {},
    'end-100': {},
    'end-50': {},
    'fixed-bottom': {},
    'fixed-top': {},
    'float-*-left': {},
    'float-*-none': {},
    'float-*-right': {},
    'float-end': {},
    'float-lg-end': {},
    'float-lg-none': {},
    'float-lg-start': {},
    'float-md-end': {},
    'float-md-none': {},
    'float-md-start': {},
    'float-none': {},
    'float-sm-end': {},
    'float-sm-none': {},
    'float-sm-start': {},
    'float-start': {},
    'float-xl-end': {},
    'float-xl-none': {},
    'float-xl-start': {},
    'float-xxl-end': {},
    'float-xxl-none': {},
    'float-xxl-start': {},
    'position-absolute': {
        position: 'absolute',
    },
    'position-relative': {},
    'position-static': {},
    'start-0': {},
    'start-100': {},
    'start-50': {},
    'sticky-lg-top': {},
    'sticky-md-top': {},
    'sticky-sm-top': {},
    'sticky-top': {},
    'sticky-xl-top': {},

    'top-0': {top: '0rem'},
    'top-1': {top: '1rem'},
    'top-2': {top: '2rem'},
    'top-3': {top: '3rem'},
    'top-4': {top: '4rem'},
    'top-5': {top: '5rem'},
    'top-6': {top: '6rem'},
    'top-7': {top: '7rem'},
    'top-8': {top: '8rem'},
    'top-9': {top: '9rem'},
    'top-10': {top: '10rem'},
    'top-11': {top: '11rem'},
    'top-12': {top: '12rem'},
    'top-13': {top: '13rem'},
    'top-14': {top: '14rem'},
    'top-15': {top: '15rem'},
    'top-16': {top: '16rem'},

    'top-100': {},
    'top-50': {},
    'translate-middle': {},

    // Progress
    'multiple progress-bar': {},
    'progress': {},
    'progress-bar': {},
    'progress-bar bg-*': {},
    'progress-bar with height': {},
    'progress-bar with label': {},
    'progress-bar-animated': {},
    'progress-bar-striped': {},
    'progress-bar-striped bg-*': {},

    // Scrollspy
    'data-spy': {},

    // Sizing
    'h-100': {},
    'h-25': {},
    'h-50': {},
    'h-75': {},
    'h-auto': {},
    'mh-100': {},
    'min-vw-100': {},
    'mw-100': {},
    'w-100': {},
    'w-25': {},
    'w-50': {},
    'w-75': {},
    'w-auto': {},

    // Spacing
    'm-1 / m-*-#': {},
    'm-auto': {},
    'm-lg-0': {},
    'm-lg-auto': {},
    'm-md-0': {},
    'm-md-auto': {},
    'm-n1 / m-*-n#': {},
    'm-sm-0': {},
    'm-sm-auto': {},
    'm-xl-0': {},
    'm-xl-auto': {},
    'm-xxl-0': {},
    'm-xxl-auto': {},
    'mb-1 / mb-*-#': {},
    'mb-auto': {},
    'mb-lg-0': {},
    'mb-lg-auto': {},
    'mb-md-0': {},
    'mb-md-auto': {},
    'mb-sm-0': {},
    'mb-sm-auto': {},
    'mb-xl-0': {},
    'mb-xl-auto': {},
    'mb-xxl-0': {},
    'mb-xxl-auto': {},
    'me-auto': {},
    'me-lg-0': {},
    'me-lg-auto': {},
    'me-md-0': {},
    'me-md-auto': {},
    'me-sm-0': {},
    'me-sm-auto': {},
    'me-xl-0': {},
    'me-xl-auto': {},
    'me-xxl-0': {},
    'me-xxl-auto': {},
    'ml-1 / ml-*-#': {},
    'mr-1 / mr-*-#': {},
    'ms-auto': {},
    'ms-lg-0': {},
    'ms-lg-auto': {},
    'ms-md-0': {},
    'ms-md-auto': {},
    'ms-sm-0': {},
    'ms-sm-auto': {},
    'ms-xl-0': {},
    'ms-xl-auto': {},
    'ms-xxl-0': {},
    'ms-xxl-auto': {},
    'mt-1 / mt-*-#': {},
    'mt-auto': {},
    'mt-lg-0': {},
    'mt-lg-auto': {},
    'mt-md-0': {},
    'mt-md-auto': {},
    'mt-sm-0': {},
    'mt-sm-auto': {},
    'mt-xl-0': {},
    'mt-xl-auto': {},
    'mt-xxl-0': {},
    'mt-xxl-auto': {},
    'mx-1 / mx-*-#': {},
    'mx-auto': {},
    'mx-lg-0': {},
    'mx-lg-auto': {},
    'mx-md-0': {},
    'mx-md-auto': {},
    'mx-sm-0': {},
    'mx-sm-auto': {},
    'mx-xl-0': {},
    'mx-xl-auto': {},
    'mx-xxl-0': {},
    'mx-xxl-auto': {},
    'my-1 / my-*-#': {},
    'my-auto': {},
    'my-lg-0': {},
    'my-lg-auto': {},
    'my-md-0': {},
    'my-md-auto': {},
    'my-sm-0': {},
    'my-sm-auto': {},
    'my-xl-0': {},
    'my-xl-auto': {},
    'my-xxl-0': {},
    'my-xxl-auto': {},
    'p-1 / p-*-#': {},
    'p-lg-0': {},
    'p-md-0': {},
    'p-sm-0': {},
    'p-xl-0': {},
    'p-xxl-0': {},
    'pb-1 / pb-*-#': {},
    'pb-lg-0': {},
    'pb-md-0': {},
    'pb-sm-0': {},
    'pb-xl-0': {},
    'pb-xxl-0': {},
    'pe-0': {},
    'pe-lg-0': {},
    'pe-md-0': {},
    'pe-sm-0': {},
    'pe-xl-0': {},
    'pe-xxl-0': {},
    'pl-1 / pl-*-#': {},
    'pr-1 / pr-*-#': {},
    'ps-0': {},
    'ps-lg-0': {},
    'ps-md-0': {},
    'ps-sm-0': {},
    'ps-xl-0': {},
    'ps-xxl-0': {},


    /**
     * Padding
     */
    'p-btn': {paddingVertical: '0.86rem', paddingHorizontal: '1rem'},
    'p-btn-sm': {paddingVertical: '0.35rem', paddingHorizontal: '0.5rem'},
    'p-half': {padding: '0.5rem'},
    'py-1-half': {padding: '1.5rem'},
    'p-0': {padding: undefined},
    'p-1': {padding: '1rem'},
    'p-2': {padding: '2rem'},
    'p-3': {padding: '3rem'},
    'p-4': {padding: '4rem'},
    'p-5': {padding: '5rem'},
    'p-6': {padding: '6rem'},
    'p-7': {padding: '7rem'},
    'p-8': {padding: '8rem'},
    'py-half': {paddingVertical: '0.5rem'},
    'py-0.75': {paddingVertical: '0.75rem'},
    'py-1': {paddingVertical: '1rem'},
    'py-2': {paddingVertical: '2rem'},
    'py-3': {paddingVertical: '3rem'},
    'py-4': {paddingVertical: '4rem'},
    'py-5': {paddingVertical: '5rem'},
    'py-6': {paddingVertical: '6rem'},
    'py-7': {paddingVertical: '7rem'},
    'py-8': {paddingVertical: '8rem'},
    'px-half': {paddingHorizontal: '0.5rem'},
    'px-1': {paddingHorizontal: '1rem'},
    'px-1-half': {paddingHorizontal: '1.5rem'},
    'px-2': {paddingHorizontal: '2rem'},
    'px-3': {paddingHorizontal: '3rem'},
    'px-4': {paddingHorizontal: '4rem'},
    'px-5': {paddingHorizontal: '5rem'},
    'px-6': {paddingHorizontal: '6rem'},
    'px-7': {paddingHorizontal: '7rem'},
    'px-8': {paddingHorizontal: '8rem'},
    'pt-0': {paddingTop: '0rem'},
    'pt-half': {paddingTop: '0.5rem'},
    'pt-1': {paddingTop: '1rem'},
    'pt-2': {paddingTop: '2rem'},
    'pt-3': {paddingTop: '3rem'},
    'pt-4': {paddingTop: '4rem'},
    'pt-5': {paddingTop: '5rem'},
    'pt-6': {paddingTop: '6rem'},
    'pt-7': {paddingTop: '7rem'},
    'pt-8': {paddingTop: '8rem'},
    'pr-half': {paddingRight: '0.5rem'},
    'pr-1': {paddingRight: '1rem'},
    'pr-1-half': {paddingRight: '1.5rem'},
    'pr-2': {paddingRight: '2rem'},
    'pr-3': {paddingRight: '3rem'},
    'pr-4': {paddingRight: '4rem'},
    'pr-5': {paddingRight: '5rem'},
    'pr-6': {paddingRight: '6rem'},
    'pr-7': {paddingRight: '7rem'},
    'pr-8': {paddingRight: '8rem'},
    'pb-0': {paddingBottom: '0rem'},
    'pb-half': {paddingBottom: '0.5rem'},
    'pb-1': {paddingBottom: '1rem'},
    'pb-2': {paddingBottom: '2rem'},
    'pb-3': {paddingBottom: '3rem'},
    'pb-4': {paddingBottom: '4rem'},
    'pb-5': {paddingBottom: '5rem'},
    'pb-6': {paddingBottom: '6rem'},
    'pb-7': {paddingBottom: '7rem'},
    'pb-8': {paddingBottom: '8rem'},
    'pl-half': {paddingLeft: '0.5rem'},
    'pl-1': {paddingLeft: '1rem'},
    'pl-2': {paddingLeft: '2rem'},
    'pl-3': {paddingLeft: '3rem'},
    'pl-4': {paddingLeft: '4rem'},
    'pl-5': {paddingLeft: '5rem'},
    'pl-6': {paddingLeft: '6rem'},
    'pl-7': {paddingLeft: '7rem'},
    'pl-8': {paddingLeft: '8rem'},


    'pt-1 / pt-*-#': {},
    'pt-lg-0': {},
    'pt-md-0': {},
    'pt-sm-0': {},
    'pt-xl-0': {},
    'pt-xxl-0': {},
    'px-0': {},
    'px-1 / px-*-#': {},
    'px-lg-0': {},
    'px-md-0': {},
    'px-sm-0': {},
    'px-xl-0': {},
    'px-xxl-0': {},
    'py-0': {},
    'py-1 / py-*-#': {},
    'py-lg-0': {},
    'py-md-0': {},
    'py-sm-0': {},
    'py-xl-0': {},
    'py-xxl-0': {},
    '        / Spinner': {},
    'spinner-border': {},
    'spinner-border text-*': {},
    'spinner-border-sm': {},
    'spinner-grow': {},
    'spinner-grow text-*': {},
    'spinner-grow-sm': {},

    // Tables
    'caption-top': {},
    'table': {},
    'table-*-responsive': {},
    'table-active': {},
    'table-bordered': {},
    'table-borderless': {},
    'table-danger': {},
    'table-dark': {},
    'table-hover': {},
    'table-info': {},
    'table-light': {},
    'table-primary': {},
    'table-reflow': {},
    'table-responsive-xxl': {},
    'table-secondary': {},
    'table-sm': {},
    'table-striped': {},
    'table-success': {},
    'table-warning': {},
    'thead-dark': {},
    'thead-light': {},

    // Text
    'font-italic': {},
    'font-weight-bold': {},
    'font-weight-bolder': {},
    'font-weight-light': {},
    'font-weight-lighter': {},
    'font-weight-normal': {},
    'text-*-center': {},
    'text-*-left': {},
    'text-*-right': {},
    'text-black-50': {},
    'text-body': {},
    'text-capitalize': {},
    'text-decoration-none': {},
    'text-hide': {},
    'text-justify': {
        textAlign: 'justify',
    },
    'text-lowercase': {},
    'text-monospace': {},
    'text-muted': {},
    'text-nowrap': {},
    'text-truncate': {},
    'text-uppercase': {},
    'text-white-50': {},

    // Toast
    'toast-body': {},
    'toast-header': {},

    // Toasts
    'toast': {},

    // Tooltips
    'tooltip': {},

    // Typography
    'blockquote': {},
    'blockquote-footer': {},
    'blockquote-reverse': {},
    'display-# (1-4)': {},
    'display-1': {},
    'display-2': {},
    'display-3': {},
    'display-4': {},
    'display-5': {},
    'display-6': {},
    'dl-horizontal': {},
    'font-monospace': {},
    'fs-1': {},
    'fs-2': {},
    'fs-3': {},
    'fs-4': {},
    'fs-5': {},
    'fs-6': {},
    'fs-lg-1': {},
    'fs-md-1': {},
    'fs-sm-1': {},
    'fst-italic': {},
    'fst-normal': {},
    'fw-bolder': {},
    'fw-light': {},
    'fw-lighter': {},
    'fw-normal': {},
    'h1': {},
    'h2': {},
    'h3': {},
    'h4': {},
    'h5': {},
    'h6': {},
    'lead': {},
    'lh-1': {},
    'lh-base': {},
    'lh-lg': {},
    'lh-sm': {},
    'list-inline': {},
    'list-unstyled': {},
    'text-break': {},
    'text-center': {
        textAlign: 'center',
    },
    'text-decoration-line-through': {},
    'text-decoration-underline': {},
    'text-end': {},
    'text-lg-center': {},
    'text-lg-end': {},
    'text-lg-start': {},
    'text-md-center': {},
    'text-md-end': {},
    'text-md-start': {},
    'text-reset': {},
    'text-sm-center': {},
    'text-sm-end': {},
    'text-sm-start': {},
    'text-start': {},
    'text-wrap': {},
    'text-xl-center': {},
    'text-xl-end': {},
    'text-xl-start': {},
    'text-xxl-center': {},
    'text-xxl-end': {},
    'text-xxl-start': {},


    /**
     * Layout and Flex
     */
    'content': {},
    'statusbar-space': {
        // paddingTop: getStatusBarHeight(undefined, true)
    },
    'col-reverse': {flexDirection: 'column-reverse'},
    'row-reverse': {flexDirection: 'row-reverse'},
    'flex-wrap': {flexWrap: 'wrap'},

    'flex-end': {alignItems: 'flex-end'},
    'flex-start': {alignItems: 'flex-start'},

    'flex': {
        flex: 1,
    },
    'flex-grow': {
        flexGrow: 1,
    },
    'flex-remove': {
        flex: 0,
        flexGrow: 0,
    },
    'inline': {alignSelf: 'flex-start'},
    'align-right': {alignSelf: 'flex-end'},
    /**
     * Available Fonts:
     * Roboto_100Thin
     * Roboto_400Regular
     * Roboto_500Medium
     * Roboto_700Bold
     * Roboto_900Black
     */
    /**
     * Text section
     */
    'text': {
        fontFamily: 'Roboto_400Regular',
        fontSize: '1rem',
        color: '$text',
    },
    'text-sm': {fontSize: '0.75rem', fontWeight: '500'},
    'text-md': {fontSize: '1.2rem', fontWeight: '500'},
    'text-lg': {fontSize: '1.4rem'},
    'text-xl': {fontSize: '2rem'},

    'text-title': {fontSize: '1.4rem'},
    'text-subtitle': {fontSize: '1.2rem'},
    'text-btn': {fontSize: '1.16rem'},
    'text-roboto-thin': {fontFamily: 'Roboto_100Thin'},
    'text-roboto-light': {fontFamily: 'Roboto_300Light'},
    'text-roboto-medium': {fontFamily: 'Roboto_500Medium'},
    'text-roboto-bold': {fontFamily: 'Roboto_700Bold'},
    'text-bold': {fontFamily: 'Roboto_700Bold'},
    'text-purple': {color: '$purple'},
    // 'text-disabled': {color: "$gray2"},
    'text-black': {color: '$black'},
    'text-light-50': {color: '$text-light-50'},
    'text-gray-1': {color: '$gray1'},
    'text-gray-2': {color: '$gray2'},
    'text-gray-3': {color: '$gray3'},
    'text-gray-4': {color: '$gray4'},
    'text-gray-5': {color: '$gray5'},
    'text-orange': {color: '$orange'},
    'text-link': {textDecorationLine: 'underline'},
    'text-align-left': {textAlign: 'left'},
    'text-align-right': {textAlign: 'right'},
    'text-align-center': {textAlign: 'center'},
    'icon': {fontSize: '1.5rem'},
    'icon-xxs': {fontSize: '0.75rem'},
    'icon-xs': {fontSize: '1rem'},
    'icon-sm': {fontSize: '1.2rem'},
    'icon-md': {fontSize: '2rem'},
    'icon-lg': {
        fontSize: '2.35rem',
    },
    'icon-xl': {
        fontSize: '3rem',
    },
    'icon-xxl': {
        fontSize: '4rem',
    },
    'icon-xxxl': {
        fontSize: '8rem',
    },
    'logo-smt-drawer': {
        fontSize: '6rem',
    },
    'icon-fullscreen': {
        fontSize: '12rem',
    },

    /**
     * Width
     */
    'width-auto': {width: 'auto'},
    'w-1': {width: '1 * $rem'},
    'w-2': {width: '2 * $rem'},
    'w-3': {width: '3 * $rem'},
    'w-4': {width: '4 * $rem'},
    'w-5': {width: '5 * $rem'},
    'w-6': {width: '6 * $rem'},
    'w-7': {width: '7 * $rem'},
    'w-8': {width: '8 * $rem'},
    'w-9': {width: '9 * $rem'},
    'w-10': {width: '10 * $rem'},
    'w-15': {width: '15 * $rem'},
    'w-20': {width: '20 * $rem'},
    'w-100-p': {width: '100%'},
    // 'ws-1': {width: '$screenWidth / 1'},
    // 'ws-16-p': {width: '$screenWidth * 0.16'},
    // 'ws-25-p': {width: '$screenWidth * 0.25'},
    // 'ws-35-p': {width: '$screenWidth * 0.35'},
    // 'ws-half': {width: '$screenWidth * 0.5'},
    // 'ws-75-p': {width: '$screenWidth * 0.75'},
    // 'ws-85-p': {width: '$screenWidth * 0.85'},
    // 'mws-85-p': {maxWidth: '$screenWidth * 0.85'},
    // 'ws-2': {width: '$screenWidth / 2'},
    // 'ws-3': {width: '$screenWidth / 3'},
    // 'ws-4': {width: '$screenWidth / 4'},
    // 'ws-5': {width: '$screenWidth / 5'},
    // 'ws-6': {width: '$screenWidth / 6'},
    // 'ws-7': {width: '$screenWidth / 7'},
    // 'ws-8': {width: '$screenWidth / 8'},

    /**
     * Height
     */
    'h-1': {height: '1rem * $rem'},
    'h-2': {height: '2rem * $rem'},
    'h-3': {height: '3rem * $rem'},
    'h-4': {height: '4rem * $rem'},
    'h-5': {height: '5rem * $rem'},
    'h-6': {height: '6rem * $rem'},
    'h-7': {height: '7rem * $rem'},
    'h-8': {height: '8rem * $rem'},
    'h-9': {height: '9rem * $rem'},
    'h-10': {height: '10rem * $rem'},
    'h-12': {height: '12rem * $rem'},
    'h-15': {height: '15rem * $rem'},
    'h-20': {height: '20rem * $rem'},


    /**
     * Width
     */
    'width-half': {width: '0.5rem'},
    'width-1': {width: '1rem'},
    'width-1-half': {width: '1.5rem'},
    'width-2': {width: '2rem'},
    'width-3': {width: '3rem'},
    'width-4': {width: '4rem'},
    'width-5': {width: '5rem'},
    'width-6': {width: '6rem'},
    'width-7': {width: '7rem'},
    'width-8': {width: '8rem'},
    'width-9': {width: '9rem'},
    'width-10': {width: '10rem'},
    'width-11': {width: '11rem'},
    'width-12': {width: '12rem'},
    'width-13': {width: '13rem'},
    'width-14': {width: '14rem'},
    'width-15': {width: '15rem'},
    'width-16': {width: '16rem'},
    'width-17': {width: '17rem'},
    'width-18': {width: '18rem'},
    'width-19': {width: '19rem'},
    'width-20': {width: '20rem'},

    /**
     * Height
     */
    'height-half': {height: '0.5rem'},
    'height-1': {height: '1rem'},
    'height-1-half': {height: '1.5rem'},
    'height-2': {height: '2rem'},
    'height-3': {height: '3rem'},
    'height-4': {height: '4rem'},
    'height-5': {height: '5rem'},
    'height-6': {height: '6rem'},
    'height-7': {height: '7rem'},
    'height-8': {height: '8rem'},
    'height-9': {height: '9rem'},
    'height-10': {height: '10rem'},
    'height-12': {height: '12rem'},
    'height-15': {height: '15rem'},
    'height-16': {height: '16rem'},
    'height-20': {height: '20rem'},
    'height-21': {height: '21rem'},
    'height-22': {height: '22rem'},

    /**
     * Max Width
     */

    // "mw-1": {maxWidth: "1rem"},
    // "mw-2": {maxWidth: "2rem"},
    // "mw-3": {maxWidth: "3rem"},
    // "mw-4": {maxWidth: "4rem"},
    // "mw-5": {maxWidth: "5rem"},
    // "mw-6": {maxWidth: "6rem"},
    // "mw-7": {maxWidth: "7rem"},
    // "mw-8": {maxWidth: "8rem"},
    // "mw-9": {maxWidth: "9rem"},
    // "mw-10": {maxWidth: "10rem"},
    // "mw-12": {maxWidth: "12rem"},
    // "mw-16": {maxWidth: "16rem"},
    // "mw-24": {maxWidth: "24rem"},
    // "mw-32": {maxWidth: "32rem"},
    // "mw-48": {maxWidth: "48rem"},
    // "mw-64": {maxWidth: "64rem"},
    // "mw-128": {maxWidth: "128rem"},

    'w-max-1': {maxWidth: '1rem'},
    'w-max-2': {maxWidth: '2rem'},
    'w-max-3': {maxWidth: '3rem'},
    'w-max-4': {maxWidth: '4rem'},
    'w-max-5': {maxWidth: '5rem'},
    'w-max-6': {maxWidth: '6rem'},
    'w-max-7': {maxWidth: '7rem'},
    'w-max-8': {maxWidth: '8rem'},
    'w-max-9': {maxWidth: '9rem'},
    'w-max-10': {maxWidth: '10rem'},
    'w-max-11': {maxWidth: '11rem'},
    'w-max-12': {maxWidth: '12rem'},
    'w-max-13': {maxWidth: '13rem'},
    'w-max-14': {maxWidth: '14rem'},
    'w-max-15': {maxWidth: '15rem'},
    'w-max-16': {maxWidth: '16rem'},
    'w-max-24': {maxWidth: '24rem'},

    'w-min-1': {minWidth: '1rem'},
    'w-min-2': {minWidth: '2rem'},
    'w-min-3': {minWidth: '3rem'},
    'w-min-4': {minWidth: '4rem'},
    'w-min-5': {minWidth: '5rem'},
    'w-min-6': {minWidth: '6rem'},
    'w-min-7': {minWidth: '7rem'},
    'w-min-8': {minWidth: '8rem'},
    'w-min-9': {minWidth: '9rem'},
    'w-min-10': {minWidth: '10rem'},
    'w-min-11': {minWidth: '11rem'},
    'w-min-12': {minWidth: '12rem'},
    'w-min-13': {minWidth: '13rem'},
    'w-min-14': {minWidth: '14rem'},
    'w-min-15': {minWidth: '15rem'},
    'w-min-16': {minWidth: '16rem'},

    'h-min-1': {minHeight: '1rem'},
    'h-min-2': {minHeight: '2rem'},
    'h-min-3': {minHeight: '3rem'},
    'h-min-4': {minHeight: '4rem'},
    'h-min-5': {minHeight: '5rem'},
    'h-min-6': {minHeight: '6rem'},
    'h-min-7': {minHeight: '7rem'},
    'h-min-8': {minHeight: '8rem'},
    'h-min-9': {minHeight: '9rem'},
    'h-min-10': {minHeight: '10rem'},
    'h-min-11': {minHeight: '11rem'},
    'h-min-12': {minHeight: '12rem'},
    'h-min-13': {minHeight: '13rem'},
    'h-min-14': {minHeight: '14rem'},
    'h-min-15': {minHeight: '15rem'},
    'h-min-16': {minHeight: '16rem'},

    /**
     * Margin
     */
    'm-half': {margin: '0.5rem'},
    'm-1': {margin: '1rem'},
    'm-2': {margin: '2rem'},
    'm-3': {margin: '3rem'},
    'm-4': {margin: '4rem'},
    'm-5': {margin: '5rem'},
    'm-6': {margin: '6rem'},
    'm-7': {margin: '7rem'},
    'm-8': {margin: '8rem'},
    'my-half': {marginVertical: '0.5rem'},
    'my-1': {marginVertical: '1rem'},
    'my-2': {marginVertical: '2rem'},
    'my-3': {marginVertical: '3rem'},
    'my-4': {marginVertical: '4rem'},
    'my-5': {marginVertical: '5rem'},
    'my-6': {marginVertical: '6rem'},
    'my-7': {marginVertical: '7rem'},
    'my-8': {marginVertical: '8rem'},
    'mx-half': {marginHorizontal: '0.5rem'},
    'mx-1': {marginHorizontal: '1rem'},
    'mx-2': {marginHorizontal: '2rem'},
    'mx-3': {marginHorizontal: '3rem'},
    'mx-4': {marginHorizontal: '4rem'},
    'mx-5': {marginHorizontal: '5rem'},
    'mx-6': {marginHorizontal: '6rem'},
    'mx-7': {marginHorizontal: '7rem'},
    'mx-8': {marginHorizontal: '8rem'},
    'mt-half': {marginTop: '0.5rem'},
    'mt-q3': {marginTop: '0.75rem'},
    'mt-1': {marginTop: '1rem'},
    'mt-2': {marginTop: '2rem'},
    'mt-3': {marginTop: '3rem'},
    'mt-4': {marginTop: '4rem'},
    'mt-5': {marginTop: '5rem'},
    'mt-6': {marginTop: '6rem'},
    'mt-7': {marginTop: '7rem'},
    'mt-8': {marginTop: '8rem'},
    'mt-half-negative': {marginTop: '-0.5rem'},
    'mt-1-negative': {marginTop: '-1rem'},
    'mt-2-negative': {marginTop: '-2rem'},
    'mt-3-negative': {marginTop: '-3rem'},
    'mt-4-negative': {marginTop: '-4rem'},
    'mt-5-negative': {marginTop: '-5rem'},
    'mt-6-negative': {marginTop: '-6rem'},
    'mt-7-negative': {marginTop: '-7rem'},
    'mt-8-negative': {marginTop: '-8rem'},
    'm-half-negative': {margin: '-0.5rem'},
    'mr-half': {marginRight: '0.5rem'},
    'mr-1': {marginRight: '1rem'},
    'mr-1-half': {marginRight: '1.5rem'},
    'mr-2': {marginRight: '2rem'},
    'mr-3': {marginRight: '3rem'},
    'mr-4': {marginRight: '4rem'},
    'mr-5': {marginRight: '5rem'},
    'mr-6': {marginRight: '6rem'},
    'mr-7': {marginRight: '7rem'},
    'mr-8': {marginRight: '8rem'},
    'mb-0': {marginBottom: '0rem'},
    'mb-half': {marginBottom: '0.5rem'},
    'mb-1': {marginBottom: '1rem'},
    'mb-2': {marginBottom: '2rem'},
    'mb-3': {marginBottom: '3rem'},
    'mb-4': {marginBottom: '4rem'},
    'mb-5': {marginBottom: '5rem'},
    'mb-6': {marginBottom: '6rem'},
    'mb-7': {marginBottom: '7rem'},
    'mb-8': {marginBottom: '8rem'},
    'mb-half-negative': {marginBottom: '-0.5rem'},
    'mb-1-negative': {marginBottom: '-1rem'},
    'mb-2-negative': {marginBottom: '-2rem'},
    'mb-3-negative': {marginBottom: '-3rem'},
    'mb-4-negative': {marginBottom: '-4rem'},
    'mb-5-negative': {marginBottom: '-5rem'},
    'mb-6-negative': {marginBottom: '-6rem'},
    'mb-7-negative': {marginBottom: '-7rem'},
    'mb-8-negative': {marginBottom: '-8rem'},
    'ml-half-negative': {marginLeft: '-0.5rem'},
    'ml-1-negative': {marginLeft: '-1rem'},
    'ml-2-negative': {marginLeft: '-2rem'},
    'ml-3-negative': {marginLeft: '-3rem'},
    'ml-4-negative': {marginLeft: '-4rem'},
    'ml-5-negative': {marginLeft: '-5rem'},
    'ml-6-negative': {marginLeft: '-6rem'},
    'ml-7-negative': {marginLeft: '-7rem'},
    'ml-8-negative': {marginLeft: '-8rem'},
    'ml-half': {marginLeft: '0.5rem'},
    'ml-1': {marginLeft: '1rem'},
    'ml-2': {marginLeft: '2rem'},
    'ml-3': {marginLeft: '3rem'},
    'ml-4': {marginLeft: '4rem'},
    'ml-5': {marginLeft: '5rem'},
    'ml-6': {marginLeft: '6rem'},
    'ml-7': {marginLeft: '7rem'},
    'ml-8': {marginLeft: '8rem'},


    /**
     * Others
     */
    'disabled': {opacity: 0.32},
    'transparent': {opacity: 0},
    'display-none': {width: 0, height: 0, opacity: 0},
    'img': {
        aspectRatio: 1,
        height: 'auto',
    },
    'img-4-9': {
        aspectRatio: 4 / 9,
        height: 'auto',
    },
    'img-16-9': {
        aspectRatio: 16 / 9,
        height: 'auto',
    },
    'img-387X81': {
        aspectRatio: 397 / 93,
        height: 'auto',
    },
    'img-272X224': {
        aspectRatio: 272 / 224,
        height: 'auto',
    },
    'img-220X42': {
        aspectRatio: 220 / 42,
        height: 'auto',
    },
    'img-146X107': {
        aspectRatio: 146 / 107,
        height: 'auto',
    },
    'avatar-navbar': {
        marginVertical: '-0.5rem',
    },
    'align-self-center': {alignSelf: 'center'},
    'align-items-center': {alignItems: 'center'},

    'center': {
        alignItems: 'center',
        justifyContent: 'center',
    },
    'b-red': {borderColor: '$danger'},
    'b-transparent': {borderColor: 'transparent'},
    'b-purple': {borderColor: '$purple'},
    'b-gray-1': {borderColor: '$gray1'},
    'b-gray-2': {borderColor: '$gray2'},
    'b-gray-3': {borderColor: '$gray3'},
    'b-gray-4': {borderColor: '$gray4'},
    'b-gray-5': {borderColor: '$gray5'},
    'b-white': {borderColor: '$white'},
    'b-warning': {borderColor: '$warning'},
    'b-primary': {borderColor: '$primary'},
    'b-orange': {borderColor: '$orange'},
    'b-danger': {borderColor: '$danger'},
    'b-success': {borderColor: '$success'},
    'badge-sm': {
        backgroundColor: '$primary',
        padding: '0.25rem',
        marginVertical: 1,
        borderRadius: 14,
        minWidth: '1.5rem',
        color: '$white',
        fontWeight: 'bold',
        alignItems: 'center',
        justifyContent: 'center',
        textAlign: 'center',
    },
    'badge-fixed': {
        position: 'absolute',
        right: '0.25rem',
        top: '-0.25rem',
    },
    'badge-fixed-2': {
        position: 'absolute',
        right: '-0.5rem',
        top: '-0.25rem',
    },
    'icon-close': {
        position: 'absolute',
        right: '0.5rem',
        top: '0.5rem',
    },
    'bl-0': {borderLeftWidth: 0, borderColor: 'transparent'},
    'br-0': {borderRightWidth: 0, borderColor: 'transparent'},
    'b-0': {borderWidth: 0, borderColor: 'transparent'},
    'b-1': {borderWidth: 1, borderColor: '$gray2'},
    'b-2': {borderWidth: 2, borderColor: '$gray2'},
    'bt-1': {borderTopWidth: 1, borderColor: '$gray2'},
    'br-1': {borderRightWidth: 1, borderColor: '$gray2'},
    'bb-0': {borderBottomWidth: 0},
    'bb-1': {borderBottomWidth: 1, borderColor: '$gray2'},
    'bl-1': {borderLeftWidth: 1, borderColor: '$gray2'},
    'bx-1': {borderLeftWidth: 1, borderRightWidth: 1, borderColor: '$gray2'},
    'by-1': {borderTopWidth: 1, borderBottomWidth: 1, borderColor: '$gray2'},
    'bt-2': {borderBottomWidth: 2, borderColor: '$gray2'},
    'br-2': {borderBottomWidth: 2, borderColor: '$gray2'},
    'bb-2': {borderBottomWidth: 2, borderColor: '$gray2'},
    'bl-2': {borderBottomWidth: 2, borderColor: '$gray2'},
    'bx-2': {borderBottomWidth: 2, borderColor: '$gray2'},
    'by-2': {borderBottomWidth: 2, borderColor: '$gray2'},
    'bt-3': {borderBottomWidth: 3, borderColor: '$gray2'},
    'br-3': {borderBottomWidth: 3, borderColor: '$gray2'},
    'bb-3': {borderBottomWidth: 3, borderColor: '$gray2'},
    'bl-3': {borderBottomWidth: 3, borderColor: '$gray2'},
    'bx-3': {borderBottomWidth: 3, borderColor: '$gray2'},
    'by-3': {borderBottomWidth: 3, borderColor: '$gray2'},
    'bt-4': {borderBottomWidth: 4, borderColor: '$gray2'},
    'br-4': {borderBottomWidth: 4, borderColor: '$gray2'},
    'bb-4': {borderBottomWidth: 4, borderColor: '$gray2'},
    'bl-4': {borderBottomWidth: 4, borderColor: '$gray2'},
    'bx-4': {borderBottomWidth: 4, borderColor: '$gray2'},
    'by-4': {borderBottomWidth: 4, borderColor: '$gray2'},
    'bt-5': {borderBottomWidth: 5, borderColor: '$gray2'},
    'br-5': {borderBottomWidth: 5, borderColor: '$gray2'},
    'bb-5': {borderBottomWidth: 5, borderColor: '$gray2'},
    'bl-5': {borderBottomWidth: 5, borderColor: '$gray2'},
    'bx-5': {borderBottomWidth: 5, borderColor: '$gray2'},
    'by-5': {borderBottomWidth: 5, borderColor: '$gray2'},
    'bt-6': {borderBottomWidth: 6, borderColor: '$gray2'},
    'br-6': {borderBottomWidth: 6, borderColor: '$gray2'},
    'bb-6': {borderBottomWidth: 6, borderColor: '$gray2'},
    'bl-6': {borderBottomWidth: 6, borderColor: '$gray2'},
    'bx-6': {borderBottomWidth: 6, borderColor: '$gray2'},
    'by-6': {borderBottomWidth: 6, borderColor: '$gray2'},

    'z-index-max': {
        position: 'absolute',
        zIndex: 9999,
    },
    'mh-input': {
        minHeight: '3rem',
    },


    'right-0': {right: '0rem'},
    'right-1': {right: '1rem'},
    'right-2': {right: '2rem'},
    'right-3': {right: '3rem'},
    'right-4': {right: '4rem'},
    'right-5': {right: '5rem'},
    'right-6': {right: '6rem'},
    'right-7': {right: '7rem'},
    'right-8': {right: '8rem'},
    'right-9': {right: '9rem'},
    'right-10': {right: '10rem'},
    'right-11': {right: '11rem'},
    'right-12': {right: '12rem'},
    'right-13': {right: '13rem'},
    'right-14': {right: '14rem'},
    'right-15': {right: '15rem'},
    'right-16': {right: '16rem'},

    'right-0-negative': {right: '-0rem'},
    'right-half-negative': {right: '-0.5rem'},
    'right-1-negative': {right: '-1rem'},
    'right-2-negative': {right: '-2rem'},
    'right-3-negative': {right: '-3rem'},
    'right-4-negative': {right: '-4rem'},
    'right-5-negative': {right: '-5rem'},
    'right-6-negative': {right: '-6rem'},
    'right-7-negative': {right: '-7rem'},
    'right-8-negative': {right: '-8rem'},
    'right-9-negative': {right: '-9rem'},
    'right-10-negative': {right: '-10rem'},
    'right-11-negative': {right: '-11rem'},
    'right-12-negative': {right: '-12rem'},
    'right-13-negative': {right: '-13rem'},
    'right-14-negative': {right: '-14rem'},
    'right-15-negative': {right: '-15rem'},
    'right-16-negative': {right: '-16rem'},

    'left-0': {left: '0rem'},
    'left-1': {left: '1rem'},
    'left-2': {left: '2rem'},
    'left-3': {left: '3rem'},
    'left-4': {left: '4rem'},
    'left-5': {left: '5rem'},
    'left-6': {left: '6rem'},
    'left-7': {left: '7rem'},
    'left-8': {left: '8rem'},
    'left-9': {left: '9rem'},
    'left-10': {left: '10rem'},
    'left-11': {left: '11rem'},
    'left-12': {left: '12rem'},
    'left-13': {left: '13rem'},
    'left-14': {left: '14rem'},
    'left-15': {left: '15rem'},
    'left-16': {left: '16rem'},


    'list-item': {
        alignSelf: 'center',
        maxWidth: '48rem',
        width: '100%',
    },

    /**
     * TODO: replace scaleY with transform
     */
    // 'invert': {scaleY: -1},
};

export default defaultClasses;
